package uk.co.jassoft.markets.eod.eoddata.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-13T13:22:32.890+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://ws.eoddata.com/Data", name = "DataSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DataSoap {

    /**
     * Returns the latest version information of Data Client.<br/>INPUT: Token (Login Token)<br/>OUTPUT: Date Client Version
     */
    @WebMethod(operationName = "DataClientLatestVersion", action = "http://ws.eoddata.com/Data/DataClientLatestVersion")
    @RequestWrapper(localName = "DataClientLatestVersion", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.DataClientLatestVersion")
    @ResponseWrapper(localName = "DataClientLatestVersionResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.DataClientLatestVersionResponse")
    @WebResult(name = "DataClientLatestVersionResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE dataClientLatestVersion(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of available exchanges.<br/>INPUT: Token (Login Token)<br/>OUTPUT: List of exchanges
     */
    @WebMethod(operationName = "ExchangeList", action = "http://ws.eoddata.com/Data/ExchangeList")
    @RequestWrapper(localName = "ExchangeList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ExchangeList")
    @ResponseWrapper(localName = "ExchangeListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ExchangeListResponse")
    @WebResult(name = "ExchangeListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE exchangeList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of News articles for a given Exchange and Symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg: AAPL)<br/>OUTPUT: List of News articles
     */
    @WebMethod(operationName = "NewsListBySymbol", action = "http://ws.eoddata.com/Data/NewsListBySymbol")
    @RequestWrapper(localName = "NewsListBySymbol", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.NewsListBySymbol")
    @ResponseWrapper(localName = "NewsListBySymbolResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.NewsListBySymbolResponse")
    @WebResult(name = "NewsListBySymbolResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE newsListBySymbol(
        @WebParam(name = "token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Returns a complete list of technical data for an entire exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "TechnicalList", action = "http://ws.eoddata.com/Data/TechnicalList")
    @RequestWrapper(localName = "TechnicalList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.TechnicalList")
    @ResponseWrapper(localName = "TechnicalListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.TechnicalListResponse")
    @WebResult(name = "TechnicalListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE technicalList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of the Top 10 Gains of a specified exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "Top10Gains", action = "http://ws.eoddata.com/Data/Top10Gains")
    @RequestWrapper(localName = "Top10Gains", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Top10Gains")
    @ResponseWrapper(localName = "Top10GainsResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Top10GainsResponse")
    @WebResult(name = "Top10GainsResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE top10Gains(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns the number of Months history a user is allowed to download.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: Number of Months
     */
    @WebMethod(operationName = "ExchangeMonths", action = "http://ws.eoddata.com/Data/ExchangeMonths")
    @RequestWrapper(localName = "ExchangeMonths", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ExchangeMonths")
    @ResponseWrapper(localName = "ExchangeMonthsResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ExchangeMonthsResponse")
    @WebResult(name = "ExchangeMonthsResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE exchangeMonths(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a URL to a chart image of a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: Chart URL
     */
    @WebMethod(operationName = "SymbolChart", action = "http://ws.eoddata.com/Data/SymbolChart")
    @RequestWrapper(localName = "SymbolChart", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolChart")
    @ResponseWrapper(localName = "SymbolChartResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolChartResponse")
    @WebResult(name = "SymbolChartResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolChart(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Login to EODData Financial Information Web Service. Used for Application Authentication.<br/>INPUT: Username, Password, Version (Application Version)<br/>OUTPUT: Login Token
     */
    @WebMethod(operationName = "Login2", action = "http://ws.eoddata.com/Data/Login2")
    @RequestWrapper(localName = "Login2", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Login2")
    @ResponseWrapper(localName = "Login2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Login2Response")
    @WebResult(name = "Login2Result", targetNamespace = "http://ws.eoddata.com/Data")
    public LOGINRESULT login2(
        @WebParam(name = "Username", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String password,
        @WebParam(name = "Version", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String version
    );

    /**
     * Returns a list of historical end of day data of a specified symbol and specified start date up to today's date.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT), StartDate (format:yyyyMMdd eg:20080225)<br/>OUTPUT: List of historical end of day quotes
     */
    @WebMethod(operationName = "SymbolHistory", action = "http://ws.eoddata.com/Data/SymbolHistory")
    @RequestWrapper(localName = "SymbolHistory", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolHistory")
    @ResponseWrapper(localName = "SymbolHistoryResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolHistoryResponse")
    @WebResult(name = "SymbolHistoryResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolHistory(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String startDate
    );

    /**
     * Returns an end of day quote for a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: End of day quote
     */
    @WebMethod(operationName = "QuoteGet", action = "http://ws.eoddata.com/Data/QuoteGet")
    @RequestWrapper(localName = "QuoteGet", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteGet")
    @ResponseWrapper(localName = "QuoteGetResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteGetResponse")
    @WebResult(name = "QuoteGetResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteGet(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Returns a complete list of end of day quotes for an entire exchange and a specific date (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteListByDate2", action = "http://ws.eoddata.com/Data/QuoteListByDate2")
    @RequestWrapper(localName = "QuoteListByDate2", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDate2")
    @ResponseWrapper(localName = "QuoteListByDate2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDate2Response")
    @WebResult(name = "QuoteListByDate2Result", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteListByDate2(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate
    );

    /**
     * Returns latest end of day quotes for a list of symbols of a specific exchange (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbols (eg:MSFT,INTC)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteList2", action = "http://ws.eoddata.com/Data/QuoteList2")
    @RequestWrapper(localName = "QuoteList2", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteList2")
    @ResponseWrapper(localName = "QuoteList2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteList2Response")
    @WebResult(name = "QuoteList2Result", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteList2(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbols", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbols
    );

    /**
     * Login to EODData Financial Information Web Service. Used for Web Authentication.<br/>INPUT: Username, Password<br/>OUTPUT: Login Token
     */
    @WebMethod(operationName = "Login", action = "http://ws.eoddata.com/Data/Login")
    @RequestWrapper(localName = "Login", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://ws.eoddata.com/Data")
    public LoginResponse login(
        @WebParam(name = "Username", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String password
    );

    /**
     * Returns a complete list of quotes for an entire exchange, specific date, and specific period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "QuoteListByDatePeriod", action = "http://ws.eoddata.com/Data/QuoteListByDatePeriod")
    @RequestWrapper(localName = "QuoteListByDatePeriod", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDatePeriod")
    @ResponseWrapper(localName = "QuoteListByDatePeriodResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDatePeriodResponse")
    @WebResult(name = "QuoteListByDatePeriodResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteListByDatePeriod(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Returns a list of historical data of a specified symbol, specified date range and specified period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT), StartDate (format:yyyyMMdd eg:20080225), EndDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of historical quotes
     */
    @WebMethod(operationName = "SymbolHistoryPeriodByDateRange", action = "http://ws.eoddata.com/Data/SymbolHistoryPeriodByDateRange")
    @RequestWrapper(localName = "SymbolHistoryPeriodByDateRange", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolHistoryPeriodByDateRange")
    @ResponseWrapper(localName = "SymbolHistoryPeriodByDateRangeResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolHistoryPeriodByDateRangeResponse")
    @WebResult(name = "SymbolHistoryPeriodByDateRangeResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolHistoryPeriodByDateRange(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String endDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Update preferred Data Format<br/>INPUT: Token (Login Token), IncludeHeader, IncludeSuffix<br/>OUTPUT: List of DataFormats
     */
    @WebMethod(operationName = "UpdateDataFormat", action = "http://ws.eoddata.com/Data/UpdateDataFormat")
    @RequestWrapper(localName = "UpdateDataFormat", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.UpdateDataFormat")
    @ResponseWrapper(localName = "UpdateDataFormatResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.UpdateDataFormatResponse")
    @WebResult(name = "UpdateDataFormatResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE updateDataFormat(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "DataFormat", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String dataFormat,
        @WebParam(name = "IncludeHeader", targetNamespace = "http://ws.eoddata.com/Data")
        boolean includeHeader,
        @WebParam(name = "IncludeSuffix", targetNamespace = "http://ws.eoddata.com/Data")
        boolean includeSuffix
    );

    /**
     * Returns a list of symbols of a specified exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of symbols
     */
    @WebMethod(operationName = "SymbolList", action = "http://ws.eoddata.com/Data/SymbolList")
    @RequestWrapper(localName = "SymbolList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolList")
    @ResponseWrapper(localName = "SymbolListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolListResponse")
    @WebResult(name = "SymbolListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns detailed information of a specific exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: Exchange
     */
    @WebMethod(operationName = "ExchangeGet", action = "http://ws.eoddata.com/Data/ExchangeGet")
    @RequestWrapper(localName = "ExchangeGet", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ExchangeGet")
    @ResponseWrapper(localName = "ExchangeGetResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ExchangeGetResponse")
    @WebResult(name = "ExchangeGetResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE exchangeGet(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of the Top 10 Losses of a specified exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "Top10Losses", action = "http://ws.eoddata.com/Data/Top10Losses")
    @RequestWrapper(localName = "Top10Losses", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Top10Losses")
    @ResponseWrapper(localName = "Top10LossesResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Top10LossesResponse")
    @WebResult(name = "Top10LossesResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE top10Losses(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns membership of user.<br/>INPUT: Token (Login Token)<br/>OUTPUT: Membership
     */
    @WebMethod(operationName = "Membership", action = "http://ws.eoddata.com/Data/Membership")
    @RequestWrapper(localName = "Membership", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.Membership")
    @ResponseWrapper(localName = "MembershipResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.MembershipResponse")
    @WebResult(name = "MembershipResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE membership(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of Splits of a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: List of splits
     */
    @WebMethod(operationName = "SplitListBySymbol", action = "http://ws.eoddata.com/Data/SplitListBySymbol")
    @RequestWrapper(localName = "SplitListBySymbol", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SplitListBySymbol")
    @ResponseWrapper(localName = "SplitListBySymbolResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SplitListBySymbolResponse")
    @WebResult(name = "SplitListBySymbolResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE splitListBySymbol(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Validate access for an entire exchange, specific date, and specific period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: RESPONSE
     */
    @WebMethod(operationName = "ValidateAccess", action = "http://ws.eoddata.com/Data/ValidateAccess")
    @RequestWrapper(localName = "ValidateAccess", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ValidateAccess")
    @ResponseWrapper(localName = "ValidateAccessResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.ValidateAccessResponse")
    @WebResult(name = "ValidateAccessResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE validateAccess(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Returns a complete list of quotes for an entire exchange, specific date, and specific period (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "QuoteListByDatePeriod2", action = "http://ws.eoddata.com/Data/QuoteListByDatePeriod2")
    @RequestWrapper(localName = "QuoteListByDatePeriod2", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDatePeriod2")
    @ResponseWrapper(localName = "QuoteListByDatePeriod2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDatePeriod2Response")
    @WebResult(name = "QuoteListByDatePeriod2Result", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteListByDatePeriod2(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Returns a list of available countries.<br/>INPUT: Token (Login Token)<br/>OUTPUT: List of countries
     */
    @WebMethod(operationName = "CountryList", action = "http://ws.eoddata.com/Data/CountryList")
    @RequestWrapper(localName = "CountryList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.CountryList")
    @ResponseWrapper(localName = "CountryListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.CountryListResponse")
    @WebResult(name = "CountryListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE countryList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns detailed information of a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: Symbol
     */
    @WebMethod(operationName = "SymbolGet", action = "http://ws.eoddata.com/Data/SymbolGet")
    @RequestWrapper(localName = "SymbolGet", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolGet")
    @ResponseWrapper(localName = "SymbolGetResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolGetResponse")
    @WebResult(name = "SymbolGetResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolGet(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Returns a list of symbol changes of a given exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of symbol changes
     */
    @WebMethod(operationName = "SymbolChangesByExchange", action = "http://ws.eoddata.com/Data/SymbolChangesByExchange")
    @RequestWrapper(localName = "SymbolChangesByExchange", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolChangesByExchange")
    @ResponseWrapper(localName = "SymbolChangesByExchangeResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolChangesByExchangeResponse")
    @WebResult(name = "SymbolChangesByExchangeResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolChangesByExchange(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a complete list of end of day quotes for an entire exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteList", action = "http://ws.eoddata.com/Data/QuoteList")
    @RequestWrapper(localName = "QuoteList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteList")
    @ResponseWrapper(localName = "QuoteListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListResponse")
    @WebResult(name = "QuoteListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns the list of data formats.<br/>INPUT: Token (Login Token)<br/>OUTPUT: List of DataFormats
     */
    @WebMethod(operationName = "DataFormats", action = "http://ws.eoddata.com/Data/DataFormats")
    @RequestWrapper(localName = "DataFormats", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.DataFormats")
    @ResponseWrapper(localName = "DataFormatsResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.DataFormatsResponse")
    @WebResult(name = "DataFormatsResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE dataFormats(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of symbols of a specified exchange (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of symbols
     */
    @WebMethod(operationName = "SymbolList2", action = "http://ws.eoddata.com/Data/SymbolList2")
    @RequestWrapper(localName = "SymbolList2", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolList2")
    @ResponseWrapper(localName = "SymbolList2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolList2Response")
    @WebResult(name = "SymbolList2Result", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolList2(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a complete list of fundamental data for an entire exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of fundamentals
     */
    @WebMethod(operationName = "FundamentalList", action = "http://ws.eoddata.com/Data/FundamentalList")
    @RequestWrapper(localName = "FundamentalList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.FundamentalList")
    @ResponseWrapper(localName = "FundamentalListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.FundamentalListResponse")
    @WebResult(name = "FundamentalListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE fundamentalList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a complete list of end of day quotes for an entire exchange and a specific date.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteListByDate", action = "http://ws.eoddata.com/Data/QuoteListByDate")
    @RequestWrapper(localName = "QuoteListByDate", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDate")
    @ResponseWrapper(localName = "QuoteListByDateResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.QuoteListByDateResponse")
    @WebResult(name = "QuoteListByDateResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE quoteListByDate(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate
    );

    /**
     * Returns a list of News articles for an entire exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of News articles
     */
    @WebMethod(operationName = "NewsList", action = "http://ws.eoddata.com/Data/NewsList")
    @RequestWrapper(localName = "NewsList", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.NewsList")
    @ResponseWrapper(localName = "NewsListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.NewsListResponse")
    @WebResult(name = "NewsListResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE newsList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of Splits of a specific exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of splits
     */
    @WebMethod(operationName = "SplitListByExchange", action = "http://ws.eoddata.com/Data/SplitListByExchange")
    @RequestWrapper(localName = "SplitListByExchange", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SplitListByExchange")
    @ResponseWrapper(localName = "SplitListByExchangeResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SplitListByExchangeResponse")
    @WebResult(name = "SplitListByExchangeResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE splitListByExchange(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of historical data of a specified symbol, specified date and specified period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT), Date (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of historical quotes
     */
    @WebMethod(operationName = "SymbolHistoryPeriod", action = "http://ws.eoddata.com/Data/SymbolHistoryPeriod")
    @RequestWrapper(localName = "SymbolHistoryPeriod", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolHistoryPeriod")
    @ResponseWrapper(localName = "SymbolHistoryPeriodResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "eoddata.SymbolHistoryPeriodResponse")
    @WebResult(name = "SymbolHistoryPeriodResult", targetNamespace = "http://ws.eoddata.com/Data")
    public RESPONSE symbolHistoryPeriod(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(name = "Date", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String date,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );
}
