package uk.co.jassoft.markets.eod.eoddata.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-05-13T13:22:32.883+01:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://ws.eoddata.com/Data", name = "DataHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DataHttpGet {

    /**
     * Returns the latest version information of Data Client.<br/>INPUT: Token (Login Token)<br/>OUTPUT: Date Client Version
     */
    @WebMethod(operationName = "DataClientLatestVersion")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE dataClientLatestVersion(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of available exchanges.<br/>INPUT: Token (Login Token)<br/>OUTPUT: List of exchanges
     */
    @WebMethod(operationName = "ExchangeList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE exchangeList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of News articles for a given Exchange and Symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg: AAPL)<br/>OUTPUT: List of News articles
     */
    @WebMethod(operationName = "NewsListBySymbol")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE newsListBySymbol(
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "symbol", name = "symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Returns a complete list of technical data for an entire exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "TechnicalList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE technicalList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of the Top 10 Gains of a specified exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "Top10Gains")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE top10Gains(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns the number of Months history a user is allowed to download.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: Number of Months
     */
    @WebMethod(operationName = "ExchangeMonths")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE exchangeMonths(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a URL to a chart image of a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: Chart URL
     */
    @WebMethod(operationName = "SymbolChart")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolChart(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Login to EODData Financial Information Web Service. Used for Application Authentication.<br/>INPUT: Username, Password, Version (Application Version)<br/>OUTPUT: Login Token
     */
    @WebMethod(operationName = "Login2")
    @WebResult(name = "LOGINRESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public LoginResponse login2(
        @WebParam(partName = "Username", name = "Username", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String username,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String password,
        @WebParam(partName = "Version", name = "Version", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String version
    );

    /**
     * Returns a list of historical end of day data of a specified symbol and specified start date up to today's date.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT), StartDate (format:yyyyMMdd eg:20080225)<br/>OUTPUT: List of historical end of day quotes
     */
    @WebMethod(operationName = "SymbolHistory")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolHistory(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(partName = "StartDate", name = "StartDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String startDate
    );

    /**
     * Returns an end of day quote for a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: End of day quote
     */
    @WebMethod(operationName = "QuoteGet")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteGet(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Returns a complete list of end of day quotes for an entire exchange and a specific date (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteListByDate2")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteListByDate2(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "QuoteDate", name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate
    );

    /**
     * Returns latest end of day quotes for a list of symbols of a specific exchange (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbols (eg:MSFT,INTC)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteList2")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteList2(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbols", name = "Symbols", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbols
    );

    /**
     * Login to EODData Financial Information Web Service. Used for Web Authentication.<br/>INPUT: Username, Password<br/>OUTPUT: Login Token
     */
    @WebMethod(operationName = "Login")
    @WebResult(name = "LOGINRESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public LoginResponse login(
        @WebParam(partName = "Username", name = "Username", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String username,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String password
    );

    /**
     * Returns a complete list of quotes for an entire exchange, specific date, and specific period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "QuoteListByDatePeriod")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteListByDatePeriod(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "QuoteDate", name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Returns a list of historical data of a specified symbol, specified date range and specified period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT), StartDate (format:yyyyMMdd eg:20080225), EndDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of historical quotes
     */
    @WebMethod(operationName = "SymbolHistoryPeriodByDateRange")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolHistoryPeriodByDateRange(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(partName = "StartDate", name = "StartDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String startDate,
        @WebParam(partName = "EndDate", name = "EndDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String endDate,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Update preferred Data Format<br/>INPUT: Token (Login Token), IncludeHeader, IncludeSuffix<br/>OUTPUT: List of DataFormats
     */
    @WebMethod(operationName = "UpdateDataFormat")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE updateDataFormat(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "DataFormat", name = "DataFormat", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String dataFormat,
        @WebParam(partName = "IncludeHeader", name = "IncludeHeader", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String includeHeader,
        @WebParam(partName = "IncludeSuffix", name = "IncludeSuffix", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String includeSuffix
    );

    /**
     * Returns a list of symbols of a specified exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of symbols
     */
    @WebMethod(operationName = "SymbolList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns detailed information of a specific exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: Exchange
     */
    @WebMethod(operationName = "ExchangeGet")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE exchangeGet(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of the Top 10 Losses of a specified exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "Top10Losses")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE top10Losses(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns membership of user.<br/>INPUT: Token (Login Token)<br/>OUTPUT: Membership
     */
    @WebMethod(operationName = "Membership")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE membership(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of Splits of a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: List of splits
     */
    @WebMethod(operationName = "SplitListBySymbol")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE splitListBySymbol(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Validate access for an entire exchange, specific date, and specific period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: RESPONSE
     */
    @WebMethod(operationName = "ValidateAccess")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE validateAccess(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "QuoteDate", name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Returns a complete list of quotes for an entire exchange, specific date, and specific period (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of quotes
     */
    @WebMethod(operationName = "QuoteListByDatePeriod2")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteListByDatePeriod2(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "QuoteDate", name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    /**
     * Returns a list of available countries.<br/>INPUT: Token (Login Token)<br/>OUTPUT: List of countries
     */
    @WebMethod(operationName = "CountryList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE countryList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns detailed information of a specific symbol.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT)<br/>OUTPUT: Symbol
     */
    @WebMethod(operationName = "SymbolGet")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolGet(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    /**
     * Returns a list of symbol changes of a given exchange. <br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of symbol changes
     */
    @WebMethod(operationName = "SymbolChangesByExchange")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolChangesByExchange(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a complete list of end of day quotes for an entire exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns the list of data formats.<br/>INPUT: Token (Login Token)<br/>OUTPUT: List of DataFormats
     */
    @WebMethod(operationName = "DataFormats")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE dataFormats(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    /**
     * Returns a list of symbols of a specified exchange (compact format).<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of symbols
     */
    @WebMethod(operationName = "SymbolList2")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolList2(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a complete list of fundamental data for an entire exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of fundamentals
     */
    @WebMethod(operationName = "FundamentalList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE fundamentalList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a complete list of end of day quotes for an entire exchange and a specific date.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), QuoteDate (format:yyyyMMdd eg:20080225)<br/>OUTPUT: List of end of day quotes
     */
    @WebMethod(operationName = "QuoteListByDate")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE quoteListByDate(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "QuoteDate", name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate
    );

    /**
     * Returns a list of News articles for an entire exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of News articles
     */
    @WebMethod(operationName = "NewsList")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE newsList(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of Splits of a specific exchange.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ)<br/>OUTPUT: List of splits
     */
    @WebMethod(operationName = "SplitListByExchange")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE splitListByExchange(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    /**
     * Returns a list of historical data of a specified symbol, specified date and specified period.<br/>INPUT: Token (Login Token), Exchange (eg: NASDAQ), Symbol (eg:MSFT), Date (format:yyyyMMdd eg:20080225), Period (1, 5, 10, 15, 30, h, d, w, m)<br/>OUTPUT: List of historical quotes
     */
    @WebMethod(operationName = "SymbolHistoryPeriod")
    @WebResult(name = "RESPONSE", targetNamespace = "http://ws.eoddata.com/Data", partName = "Body")
    public RESPONSE symbolHistoryPeriod(
        @WebParam(partName = "Token", name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(partName = "Exchange", name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(partName = "Symbol", name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(partName = "Date", name = "Date", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String date,
        @WebParam(partName = "Period", name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );
}
